import { toDate } from "@/lib/time";
import { MESSAGE_TYPE } from "@/lib/constants";
import type { CwMessage } from "@/lib/chatwoot/types";

export interface NormalizedMessage {
  chatwootId: number;
  messageType: number | null;
  contentType: string | null;
  private: boolean;
  content: string | null;
  senderType: string | null;
  senderId: number | null;
  senderName: string | null;
  createdAt: Date | null;
  isTemplate: boolean;
  isAutomation: boolean;
  isBot: boolean;
  isHumanReply: boolean;
  isCustomerIncoming: boolean;
}

/**
 * Chatwoot stamps machine-generated sends in `content_attributes`:
 *   automation_rule_id → produced by an automation rule (sender is nil)
 *   campaign_id        → produced by a Chatwoot campaign
 *   template_params    → a WhatsApp template send (what the campaign uploader uses)
 */
function contentAttr(raw: CwMessage, key: string): unknown {
  const attrs = raw.content_attributes as Record<string, unknown> | undefined;
  return attrs?.[key];
}

function present(value: unknown): boolean {
  return value !== undefined && value !== null && value !== "";
}

/**
 * Classify a single Chatwoot message. The crucial rule for Engosoft:
 * a "human reply" is a PUBLIC OUTGOING message sent by an identifiable human
 * agent. Everything else is excluded from response-time metrics —
 *   • private notes            (agents talking to each other)
 *   • WhatsApp campaign templates and Chatwoot campaign sends
 *   • automation-rule messages (no human decided to send them)
 *   • Fahd/Botpress and any other agent_bot
 *   • incoming and activity messages
 * An outgoing public message with no sender is machine-generated by definition
 * (Chatwoot builds automation/campaign messages with a nil sender), so it never
 * counts as a human reply.
 */
export function classifyMessage(raw: CwMessage, botAgentIds: Set<number>): NormalizedMessage {
  const messageType = typeof raw.message_type === "number" ? raw.message_type : null;
  const isPrivate = raw.private === true;
  const senderType = String(raw.sender?.type || raw.sender_type || "").toLowerCase() || null;
  const senderId = typeof raw.sender?.id === "number" ? raw.sender.id : null;

  const isTemplate =
    messageType === MESSAGE_TYPE.template ||
    present(contentAttr(raw, "template_params")) ||
    present(contentAttr(raw, "campaign_id"));

  const isAutomation = present(contentAttr(raw, "automation_rule_id"));

  const isContactSender = senderType === "contact";
  const isBot =
    !isContactSender &&
    ((senderType !== null && senderType.includes("agent_bot")) ||
      (senderId !== null && botAgentIds.has(senderId)));

  // A real agent reply always carries the agent as sender. No sender ⇒ system.
  const hasHumanSender = senderId !== null && !isContactSender && !isBot;

  const isOutgoingPublic = messageType === MESSAGE_TYPE.outgoing && !isPrivate;
  const isHumanReply = isOutgoingPublic && hasHumanSender && !isTemplate && !isAutomation;
  const isCustomerIncoming = messageType === MESSAGE_TYPE.incoming && !isPrivate;

  return {
    chatwootId: raw.id,
    messageType,
    contentType: raw.content_type ?? null,
    private: isPrivate,
    content: raw.content ?? null,
    senderType,
    senderId,
    senderName: raw.sender?.name ?? raw.sender?.available_name ?? null,
    createdAt: toDate(raw.created_at),
    isTemplate,
    isAutomation,
    isBot,
    isHumanReply,
    isCustomerIncoming,
  };
}

export function normalizeMessages(messages: CwMessage[], botAgentIds: Set<number>): NormalizedMessage[] {
  return messages
    .map((m) => classifyMessage(m, botAgentIds))
    .sort((a, b) => (a.createdAt?.getTime() ?? 0) - (b.createdAt?.getTime() ?? 0));
}
